"""Initial migration: create pad table

Revision ID: 63af0bb4b1ba
Revises: 
Create Date: 2025-11-08 20:58:18.480858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63af0bb4b1ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=64), nullable=False),
    sa.Column('syntax', sa.String(length=16), nullable=True),
    sa.Column('data', sa.UnicodeText(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('wordwrap', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('ip_addr', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pad')
    # ### end Alembic commands ###
